version: "3.8"
   
services:
  frontend:
    build: .
    container_name: vuejs-frontend
    volumes:
      - ./:/app/src
    ports:
      - "3000:3000"
#    entrypoint: "bash -c 'while true; do sleep 2; done'"
